try {
    // Will produce a ReferenceError
    myFunction();
} catch (error) {
    console.log(error)
}